global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mvme'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:13802']
