R"(
ROOTCFLAGS	=	$(shell root-config --cflags)
ROOTLIBS	=	$(shell root-config --libs)
INCLUDES    =	-I$(MVME) -I$(MVME)/include

CXXFLAGS   +=	-std=c++14
CXXFLAGS   +=   $(INCLUDES)
MVMELIBS    =   -L$(MVME) -L$(MVME)/lib -lmvme_root_event

.PHONY: all clean

EXP_LIB		= lib{{exp_name}}_mvme.so
EXP_DICT	= lib{{exp_name}}_mvme_dict.cxx
EXP_LINKDEF = {{exp_name}}_mvme_LinkDef.h

ALL_TARGETS	= $(EXP_LIB) analysis.so
ANALYSIS_DEPS =
ANALYSIS_LIBS =

# Customization point for user analysis
include analysis.mk

all: $(ALL_TARGETS)

$(EXP_DICT): {{impl_filename}} {{header_filename}} $(EXP_LINKDEF)
	rootcling -f $@ -rml $(EXP_LIB) -rmf lib{{exp_name}}_mvme.rootmap $(INCLUDES) {{header_filename}} $(EXP_LINKDEF)

$(EXP_LIB): {{impl_filename}} {{header_filename}} $(EXP_DICT)
	$(CXX) $(LDFLAGS) $(ROOTCFLAGS) $(CXXFLAGS) $(ROOTLIBS) $(MVMELIBS) -shared -fPIC -o $@ $<

analysis.so: $(EXP_LIB)
	$(CXX) $(LDFLAGS) $(ROOTCFLAGS) $(CXXFLAGS) $(ROOTLIBS) $(MVMELIBS) $(ANALYSIS_LIBS) -Wl,-rpath,. -L. -l{{exp_name}}_mvme -shared -fPIC -o $@ $<

{{!
vim:ft=make
}})"
