######################################################################
# Automatically generated by qmake (3.0) Mon Sep 26 13:21:51 2016
######################################################################

TEMPLATE = app
TARGET = vme_script
INCLUDEPATH += .
QT       += core gui concurrent widgets
CONFIG   += c++11
QMAKE_CXXFLAGS += -Wno-unused -Wno-format
QMAKE_CFLAGS += -Wno-unused -Wno-format

# Input
HEADERS += vme_script_qt.h
SOURCES += vme_script_qt.cc
