#include "listfile_recovery.h"

/* Utilitiues to recover ZIP archives generated by mvme that got corrupted due to
 * a crash or power outage or similar.
 *
 * Based on BruteZip by Jason A. Donenfeld, https://git.zx2c4.com/BruteZip/about/
 */

namespace
{

typedef struct
{
	uint32_t sig __attribute__ ((packed));
	uint16_t version __attribute__ ((packed));
	uint16_t gen __attribute__ ((packed));
	uint16_t compression __attribute__ ((packed));
	uint16_t modtime __attribute__ ((packed));
	uint16_t moddate __attribute__ ((packed));
	uint32_t crc32 __attribute__ ((packed));
	uint32_t compressedsize __attribute__ ((packed));
	uint32_t uncompressedsize __attribute__ ((packed));
	uint16_t filenamelength __attribute__ ((packed));
	uint16_t extrafieldlength __attribute__ ((packed));
} lfh;
}

namespace mesytec::mvme::listfile_recovery
{
}