find_path(GRAPHVIZ_INCLUDE_DIR NAMES cgraph.h PATH_SUFFIXES graphviz)

find_library(GRAPHVIZ_CDT_LIBRARY cdt PATH_SUFFIXES graphviz)
find_library(GRAPHVIZ_CGRAPH_LIBRARY cgraph PATH_SUFFIXES graphviz)
find_library(GRAPHVIZ_GVC_LIBRARY gvc PATH_SUFFIXES graphviz)

set(GRAPHVIZ_INCLUDE_DIRS ${GRAPHVIZ_INCLUDE_DIR})
set(GRAPHVIZ_LIBRARIES ${GRAPHVIZ_CDT_LIBRARY} ${GRAPHVIZ_CGRAPH_LIBRARY} ${GRAPHVIZ_GVC_LIBRARY})
